[package]
name = "game"
version = "0.1.0"

build = "build.rs"

[dependencies]
tetrs = { path = "../tetrs" }
rand = "0.3"

[dependencies.sdl2]
version = "0.29"
default-features = false
features = ["image"]
